- name: install ZSH
  apt: name=zsh
  tags: 
  - zsh
- name: change default shell to ZSH
  shell: chsh -s `which zsh`
  tags: 
  - zsh
- name: install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags: 
  - zsh
- name: install zsh plugin zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/plugins/zsh-autosuggestions
  tags: 
  - zsh
